web: target/universal/stage/bin/$NOME_DO_SEU_PROJETO -Dhttp.port=${PORT}
-DapplyEvolutions.default=true -Ddb.default.driver=org.postgresql.Driver
-Ddb.default.url=${DATABASE_URL} -Djpa.default=postgrePersistenceUnit
